// Code generated by `make stamp` (run automatically by `make lib` / `make libs`).
// DO NOT EDIT.

package mmdr

// archiveStamp is a digest of the prebuilt static archives under lib/. It exists
// solely to keep Go's build cache honest, and is never read at runtime.
//
// cgo names the archive by path (`#cgo LDFLAGS: -L${SRCDIR}/lib/... -lmmdr`), and
// Go hashes the LDFLAGS *text*, not the archive's contents. So after rebuilding
// libmmdr.a, the package's cache key is unchanged and `go test` will happily
// relink the STALE archive — silently testing the old engine. Regenerating this
// constant changes a source file in the package, which changes the cache key and
// forces the relink.
//
// If you rebuild an archive by hand instead of via make, run `make stamp` (or
// `go clean -cache`) or you will not be testing what you just built.
const archiveStamp = "sha256:b73891ab589809c05daa9a79d9eebcb48dc477c1314e4e9af256ae748db2a47b"

var _ = archiveStamp
